-- Run this in Supabase SQL Editor.
-- Also create a public Storage bucket named "clips" in Storage.

create table if not exists public.verdicts (
  id bigint generated by default as identity primary key,
  clip_id text not null unique,
  video_url text,
  sport text not null default 'basketball',
  level_of_play text,
  league text,
  original_call text,
  referee_name text,
  verdict text,
  confidence numeric,
  call_type text,
  rule_id text,
  reasoning text,
  votes_fair integer not null default 0,
  votes_bad integer not null default 0,
  votes_inconclusive integer not null default 0,
  verdict_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists verdicts_created_at_idx
  on public.verdicts (created_at desc);

create index if not exists verdicts_verdict_idx
  on public.verdicts (verdict);
